services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: producer
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    depends_on:
      rabbitmq:
        condition: service_healthy
  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    container_name: consumer
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    depends_on:
      rabbitmq:
        condition: service_healthy
 